#!/bin/bash -e
### BEGIN INIT INFO
# Provides:          net-smp-affinity
# Required-Start:
# Required-Stop:
# Default-Start: 5
# Default-Stop: 6
# Short-Description:
# Description:       Bind network device interrupts to target cpu
### END INIT INFO

get_device_irq() {
	local device="$1"
	local line
	local seconds="0"

	# wait up to 10 seconds for the irq/device to appear
	while [ "${seconds}" -le 10 ]; do
		line=$(grep -m 1 "${device}\$" /proc/interrupts) && break
		seconds="$(( seconds + 2 ))"
		sleep 2
	done
	echo ${line} | sed 's/:.*//'
}

set_interface_core() {
	local core_mask="$1"
	local interface="$2"
	local device="$3"

	[ -z "${device}" ] && device="$interface"

	local irq=$(get_device_irq "$device")

	echo "${core_mask}" > /proc/irq/${irq}/smp_affinity
}

COMPATIBLE=$(cat /proc/device-tree/compatible)
if [[ $COMPATIBLE =~ "rk3308" ]]; then
	set_interface_core 2 "eth0"
	set_interface_core 4 "eth1" "ehci_hcd:usb2"
fi
