// Generated by gencpp from file hesai_ros_driver/Firetime.msg
// DO NOT EDIT!


#ifndef HESAI_ROS_DRIVER_MESSAGE_FIRETIME_H
#define HESAI_ROS_DRIVER_MESSAGE_FIRETIME_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hesai_ros_driver
{
template <class ContainerAllocator>
struct Firetime_
{
  typedef Firetime_<ContainerAllocator> Type;

  Firetime_()
    : data()  {
      data.assign(0.0);
  }
  Firetime_(const ContainerAllocator& _alloc)
    : data()  {
  (void)_alloc;
      data.assign(0.0);
  }



   typedef boost::array<double, 512>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::hesai_ros_driver::Firetime_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hesai_ros_driver::Firetime_<ContainerAllocator> const> ConstPtr;

}; // struct Firetime_

typedef ::hesai_ros_driver::Firetime_<std::allocator<void> > Firetime;

typedef boost::shared_ptr< ::hesai_ros_driver::Firetime > FiretimePtr;
typedef boost::shared_ptr< ::hesai_ros_driver::Firetime const> FiretimeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hesai_ros_driver::Firetime_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hesai_ros_driver::Firetime_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hesai_ros_driver::Firetime_<ContainerAllocator1> & lhs, const ::hesai_ros_driver::Firetime_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hesai_ros_driver::Firetime_<ContainerAllocator1> & lhs, const ::hesai_ros_driver::Firetime_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hesai_ros_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hesai_ros_driver::Firetime_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hesai_ros_driver::Firetime_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hesai_ros_driver::Firetime_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hesai_ros_driver::Firetime_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hesai_ros_driver::Firetime_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hesai_ros_driver::Firetime_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hesai_ros_driver::Firetime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "869425aed297bb57ab8d72e8d4c6bc7d";
  }

  static const char* value(const ::hesai_ros_driver::Firetime_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x869425aed297bb57ULL;
  static const uint64_t static_value2 = 0xab8d72e8d4c6bc7dULL;
};

template<class ContainerAllocator>
struct DataType< ::hesai_ros_driver::Firetime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hesai_ros_driver/Firetime";
  }

  static const char* value(const ::hesai_ros_driver::Firetime_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hesai_ros_driver::Firetime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[512] data\n"
;
  }

  static const char* value(const ::hesai_ros_driver::Firetime_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hesai_ros_driver::Firetime_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Firetime_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hesai_ros_driver::Firetime_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hesai_ros_driver::Firetime_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    if (v.data.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.data[i]);
    }
    if (v.data.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // HESAI_ROS_DRIVER_MESSAGE_FIRETIME_H
