// Generated by gencpp from file hesai_ros_driver/LossPacket.msg
// DO NOT EDIT!


#ifndef HESAI_ROS_DRIVER_MESSAGE_LOSSPACKET_H
#define HESAI_ROS_DRIVER_MESSAGE_LOSSPACKET_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hesai_ros_driver
{
template <class ContainerAllocator>
struct LossPacket_
{
  typedef LossPacket_<ContainerAllocator> Type;

  LossPacket_()
    : total_packet_count(0)
    , total_packet_loss_count(0)  {
    }
  LossPacket_(const ContainerAllocator& _alloc)
    : total_packet_count(0)
    , total_packet_loss_count(0)  {
  (void)_alloc;
    }



   typedef uint32_t _total_packet_count_type;
  _total_packet_count_type total_packet_count;

   typedef uint32_t _total_packet_loss_count_type;
  _total_packet_loss_count_type total_packet_loss_count;





  typedef boost::shared_ptr< ::hesai_ros_driver::LossPacket_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hesai_ros_driver::LossPacket_<ContainerAllocator> const> ConstPtr;

}; // struct LossPacket_

typedef ::hesai_ros_driver::LossPacket_<std::allocator<void> > LossPacket;

typedef boost::shared_ptr< ::hesai_ros_driver::LossPacket > LossPacketPtr;
typedef boost::shared_ptr< ::hesai_ros_driver::LossPacket const> LossPacketConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hesai_ros_driver::LossPacket_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hesai_ros_driver::LossPacket_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hesai_ros_driver::LossPacket_<ContainerAllocator1> & lhs, const ::hesai_ros_driver::LossPacket_<ContainerAllocator2> & rhs)
{
  return lhs.total_packet_count == rhs.total_packet_count &&
    lhs.total_packet_loss_count == rhs.total_packet_loss_count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hesai_ros_driver::LossPacket_<ContainerAllocator1> & lhs, const ::hesai_ros_driver::LossPacket_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hesai_ros_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hesai_ros_driver::LossPacket_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hesai_ros_driver::LossPacket_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hesai_ros_driver::LossPacket_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hesai_ros_driver::LossPacket_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hesai_ros_driver::LossPacket_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hesai_ros_driver::LossPacket_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hesai_ros_driver::LossPacket_<ContainerAllocator> >
{
  static const char* value()
  {
    return "363355020f4e7cc5a0f379abeda225bc";
  }

  static const char* value(const ::hesai_ros_driver::LossPacket_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x363355020f4e7cc5ULL;
  static const uint64_t static_value2 = 0xa0f379abeda225bcULL;
};

template<class ContainerAllocator>
struct DataType< ::hesai_ros_driver::LossPacket_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hesai_ros_driver/LossPacket";
  }

  static const char* value(const ::hesai_ros_driver::LossPacket_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hesai_ros_driver::LossPacket_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 total_packet_count\n"
"uint32 total_packet_loss_count\n"
;
  }

  static const char* value(const ::hesai_ros_driver::LossPacket_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hesai_ros_driver::LossPacket_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.total_packet_count);
      stream.next(m.total_packet_loss_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LossPacket_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hesai_ros_driver::LossPacket_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hesai_ros_driver::LossPacket_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "total_packet_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.total_packet_count);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "total_packet_loss_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.total_packet_loss_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HESAI_ROS_DRIVER_MESSAGE_LOSSPACKET_H
