// Generated by gencpp from file hesai_ros_driver/Ptp.msg
// DO NOT EDIT!


#ifndef HESAI_ROS_DRIVER_MESSAGE_PTP_H
#define HESAI_ROS_DRIVER_MESSAGE_PTP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hesai_ros_driver
{
template <class ContainerAllocator>
struct Ptp_
{
  typedef Ptp_<ContainerAllocator> Type;

  Ptp_()
    : ptp_lock_offset(0)
    , ptp_status()  {
      ptp_status.assign(0);
  }
  Ptp_(const ContainerAllocator& _alloc)
    : ptp_lock_offset(0)
    , ptp_status()  {
  (void)_alloc;
      ptp_status.assign(0);
  }



   typedef uint8_t _ptp_lock_offset_type;
  _ptp_lock_offset_type ptp_lock_offset;

   typedef boost::array<uint8_t, 16>  _ptp_status_type;
  _ptp_status_type ptp_status;





  typedef boost::shared_ptr< ::hesai_ros_driver::Ptp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hesai_ros_driver::Ptp_<ContainerAllocator> const> ConstPtr;

}; // struct Ptp_

typedef ::hesai_ros_driver::Ptp_<std::allocator<void> > Ptp;

typedef boost::shared_ptr< ::hesai_ros_driver::Ptp > PtpPtr;
typedef boost::shared_ptr< ::hesai_ros_driver::Ptp const> PtpConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hesai_ros_driver::Ptp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hesai_ros_driver::Ptp_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hesai_ros_driver::Ptp_<ContainerAllocator1> & lhs, const ::hesai_ros_driver::Ptp_<ContainerAllocator2> & rhs)
{
  return lhs.ptp_lock_offset == rhs.ptp_lock_offset &&
    lhs.ptp_status == rhs.ptp_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hesai_ros_driver::Ptp_<ContainerAllocator1> & lhs, const ::hesai_ros_driver::Ptp_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hesai_ros_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hesai_ros_driver::Ptp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hesai_ros_driver::Ptp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hesai_ros_driver::Ptp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hesai_ros_driver::Ptp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hesai_ros_driver::Ptp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hesai_ros_driver::Ptp_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hesai_ros_driver::Ptp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "17a101cc667a4bf8eccaf77e6e093ba0";
  }

  static const char* value(const ::hesai_ros_driver::Ptp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x17a101cc667a4bf8ULL;
  static const uint64_t static_value2 = 0xeccaf77e6e093ba0ULL;
};

template<class ContainerAllocator>
struct DataType< ::hesai_ros_driver::Ptp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hesai_ros_driver/Ptp";
  }

  static const char* value(const ::hesai_ros_driver::Ptp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hesai_ros_driver::Ptp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 ptp_lock_offset\n"
"uint8[16] ptp_status\n"
;
  }

  static const char* value(const ::hesai_ros_driver::Ptp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hesai_ros_driver::Ptp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ptp_lock_offset);
      stream.next(m.ptp_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ptp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hesai_ros_driver::Ptp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hesai_ros_driver::Ptp_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "ptp_lock_offset: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ptp_lock_offset);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ptp_status: ";
    if (v.ptp_status.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.ptp_status.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.ptp_status[i]);
    }
    if (v.ptp_status.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // HESAI_ROS_DRIVER_MESSAGE_PTP_H
