set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(RK3588_SDK_ROOT ${CMAKE_CURRENT_LIST_DIR}/../../rk3588_sdk)

set(CMAKE_C_COMPILER   ${RK3588_SDK_ROOT}/bin/aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER ${RK3588_SDK_ROOT}/bin/aarch64-linux-gnu-g++)

set(CMAKE_FIND_ROOT_PATH ${RK3588_SDK_ROOT}/aarch64-linux-gnu)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

add_definitions(-DRK3588 -DARM64)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3 -march=armv8-a -mtune=cortex-a76")