<?xml version="1.0"?>
<package format="2">
  <name>lawnmower_base</name>
  <version>0.0.0</version>
  <description>Lawnmower base control node</description>
  <maintainer email="support@example.com">Your Company</maintainer>
  <license>MIT</license>
  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>roscpp</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>tf2_ros</build_depend>
  <build_depend>handsfree_rtk</build_depend>
  <build_depend>orbbec_camera</build_depend>
  <build_depend>Hesai_Lidar</build_depend>
  <run_depend>roscpp</run_depend>
  <run_depend>sensor_msgs</run_depend>
  <run_depend>tf2_ros</run_depend>
  <run_depend>handsfree_rtk</run_depend>
  <run_depend>orbbec_camera</run_depend>
  <run_depend>Hesai_Lidar</run_depend>
</package>