<?xml version="1.0"?>
<package format="2">
  <name>rk3588_sdk</name>
  <version>0.0.0</version>
  <description>RK3588 platform SDK</description>
  <maintainer email="support@example.com">Your Company</maintainer>
  <license>MIT</license>
  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>roscpp</build_depend>
  <build_depend>serial</build_depend>
  <run_depend>roscpp</run_depend>
  <run_depend>serial</run_depend>
</package>