orbbec_gemini335:
  usb_port: "/dev/ttyUSB0"    # RK3588 USB端口
  baudrate: 921600            # 通信波特率
  frame_rate: 30              # 图像帧率
  resolution: "1280x720"      # 图像分辨率
  auto_exposure: true         # 自动曝光开关
  exposure_value: 100         # 手动曝光值（auto_exposure=false时生效）
  baseline: 0.06              # 相机基线长度(m)
  enable_imu: true            # 是否启用内置IMU
  topic_name: "/lawnmower/orbbec/stereo_image" # 数据发布话题名