lidar:
  - driver:
      use_gpu: false
      source_type: 1  # 1: real-time lidar connection, 2: pcap, 3: packet rosbag, 4: serial
      lidar_udp_type:
        device_ip_address: 192.168.1.201  # host_ip_address. If empty(""), the source ip of the udp point cloud is used
        udp_port: 2368  # UDP destination port
        ptc_port: 9347  # PTC port of lidar
        multicast_ip_address: 255.255.255.255
        use_ptc_connected: true  # Set to false when ptc connection is not used
        correction_file_path: "Your correction file path"  # The path of correction file
        firetimes_path: "Your firetime file path"  # The path of firetimes file
        use_someip: false
        host_ip_address: ""
        fault_message_port: 0
        standby_mode: -1  # The standby mode: [-1] is invalid [0] in operation [1] standby
        speed: -1  # The speed: [-1] invalid, you must make sure your set has been supported by the lidar you are using
        ptc_mode: 0  # The ptc mode: [0] tcp [1] tcp_ssl