#!/bin/sh
set -e
# Automatically added by dh_installdeb/12.10ubuntu1
dpkg-maintscript-helper mv_conffile /etc/xdg/xdg-xubuntu/Terminal/terminalrc /etc/xdg/xdg-xubuntu/xfce4/terminal/terminalrc 13.04.0\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/lightdm/lightdm-gtk-greeter.conf.d/30_xubuntu.conf 16.04.1 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/lightdm/lightdm.conf.d/10-xubuntu.conf 14.04.4 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/skel/.config/gtk-3.0/gtk.css 15.04.0 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xdg/xdg-xubuntu/autostart/light-locker.desktop 15.04.3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xdg/xdg-xubuntu/autostart/xfce4-tips-autostart.desktop 19.10.2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xdg/xdg-xubuntu/lightdm/lightdm-gtk-greeter.conf 16.04.1 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xdg/xdg-xubuntu/Thunar/thunarrc 13.04.1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xdg/xdg-xubuntu/xfce4/panel/datetime-7.rc 12.10.2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xdg/xdg-xubuntu/xfce4/panel/indicator-5.rc 12.10.1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xdg/xdg-xubuntu/xfce4/xfconf/xfce-perchannel-xml/xfprint.xml 19.10.2\~ -- "$@"
# End automatically added section
