<?xml version="1.0"?>
<package format="2">
  <name>motor_control</name>
  <version>0.0.0</version>
  <description>Motor control node</description>
  <maintainer email="support@example.com">Your Company</maintainer>
  <license>MIT</license>
  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>roscpp</build_depend>
  <build_depend>geometry_msgs</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>rk3588_sdk</build_depend>
  <run_depend>roscpp</run_depend>
  <run_depend>geometry_msgs</run_depend>
  <run_depend>sensor_msgs</run_depend>
  <run_depend>rk3588_sdk</run_depend>
</package>