<?xml version="1.0"?>
<package format="2">
  <name>orbbec_camera</name>
  <version>0.0.0</version>
  <description>Orbbec Gemini335 stereo camera driver</description>
  <maintainer email="support@example.com">Your Company</maintainer>
  <license>MIT</license>
  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>roscpp</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>image_transport</build_depend>
  <build_depend>cv_bridge</build_depend>
  <build_depend>libusb-1.0</build_depend>
  <run_depend>roscpp</run_depend>
  <run_depend>sensor_msgs</run_depend>
  <run_depend>image_transport</run_depend>
  <run_depend>cv_bridge</run_depend>
</package>